# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 spatterIight
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Wetty systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wetty_identifier }}.service"
  register: wetty_service_stat

- name: Uninstall Wetty systemd services and files
  when: wetty_service_stat.stat.exists | bool
  block:
    - name: Ensure Wetty systemd service is stopped
      ansible.builtin.service:
        name: "{{ wetty_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Wetty systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wetty_identifier }}.service"
        state: absent

    - name: Ensure Wetty container network does not exist
      when: wetty_container_network_deletion_enabled
      block:
        - name: Ensure Wetty container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ wetty_container_network }}"
            state: absent
          register: wetty_network_deletion_result

        - name: Ensure Wetty container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ wetty_container_network }}
          register: wetty_network_deletion_result
          changed_when: wetty_container_network in wetty_network_deletion_result.stdout

    - name: Ensure Wetty path does not exist
      ansible.builtin.file:
        path: "{{ wetty_base_path }}"
        state: absent
